### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/bomi#1]
Don't just copy/paste, then there is no use whatsoever to have KCP
Follow the formatting standards, don't set maintainers (especially non-existing in KCP):
http://kaosx.us/kcp-guide/#Formatting_standards_for_KCP
There is no libpulse in KaOS, check the needed python, there is no just python in KaOS, there is no "cmplayer" in KaOS, so why a conflict?  This is a first submit, so ofc pkrel is not 3 then.

This addition will not stay in KCP as is, needs to be cleaned up or it will be removed shortly.

**Comment by tigerroast** [comment]
Apologies. This is the first time I'm attempting to do anything on GitHub. I will be working on it immediately.

**Comment by tigerroast** [comment]
I believe that was the last of the discrepancies in this PKGBUILD. Once again, apologies for posting such a mess. This is the first time I've ever packaged anything for a distribution. Thank you for catching those mistakes.

**Comment by demmm** [comment]
Thanks for the quick fix
